services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    pull_policy: always
    ports:
      - 8096:8096
    volumes:
      - /mnt/media/configs/jellyfin:/config
      - /mnt/media/media:/media
    devices:
       - /dev/dri:/dev/dri
   
    environment:
      - LIBVA_DRIVER_NAME=iHD
      - VAAPI_DRIVER=iHD
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    pull_policy: always
    ports:
      - 7878:7878
    volumes:
      - /mnt/media/configs/radarr:/config
      - /mnt/media/media/movies:/movies
      - /mnt/media/Downloads:/downloads
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    pull_policy: always
    ports:
      - 8989:8989
    volumes:
      - /mnt/media/configs/sonarr:/config
      - /mnt/media/media/shows:/shows
      - /mnt/media/Downloads:/downloads
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    pull_policy: always
    ports:
      - 9696:9696
    volumes:
      - /mnt/media/configs/prowlarr:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    pull_policy: always
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /mnt/media/configs/qbittorrent:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/media:/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - WEBUI_PORT=8080

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /mnt/media/bazarr/config:/config
      - /mnt/media/media/movies:/movies
      - /mnt/media/media/shows:/shows
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    pull_policy: always
    ports:
      - 9117:9117
    volumes:
      - /mnt/media/configs/jackett:/config
      - /mnt/media/Downloads:/downloads
      - /mnt/media/media:/media
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    pull_policy: always
    ports:
      - 80:80
      - 81:81   # Admin UI
      - 443:443
    volumes:
      - /mnt/media/configs/npm/data:/data
      - /mnt/media/configs/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  default:
    driver: bridge

